first_num = int(input("Give me the first number: "))
second_num = int(input("Give me the second number: "))
print("Thank you!")
print(first_num , "+" , second_num , "=" , first_num + second_num)
print(first_num , "-" , second_num , "=" , first_num - second_num)
print(first_num , "*" , second_num , "=" , first_num * second_num)
print(first_num , "/" , second_num , "=" , first_num / second_num)